[package]
name = "gargantua"
version = "0.2.0"
authors = ["Bryant Luk <bryant.luk@bryantluk.com>"]
edition = "2021"

[dependencies]
dotenv = "0.15"

tracing = "0.1.32"
tracing-subscriber = "0.3.9"

serde = "1.0.136"
serde_derive = "1.0.136"
serde_json = "1.0.79"

uuid = { version = "0.8.2", features = ["serde", "v4"] }

httpdate = "1.0.2"

axum = "0.4.8"
hyper = { version = "0.14.18", features = ["full"] }
http = { version = "0.2.6" }
tokio = { version = "1.17.0", features = ["full"] }
tower = "0.4.12"
tower-http = { version = "0.2.5", features = ["request-id", "trace", "util"] }