[package]
name = "gargantua"
version = "0.2.0"
authors = ["Bryant Luk <bryant.luk@bryantluk.com>"]
edition = "2021"

[dependencies]
dotenv = "0.15"

tracing = "0.1.29"
tracing-subscriber = "0.3.6"

serde = { version = "1.0.135", features = ["derive"] }
serde_json = "1.0.78"

uuid = { version = "0.8.2", features = ["serde", "v4"] }

httpdate = "1.0.2"

axum = "0.4.4"
hyper = { version = "0.14.16", features = ["full"] }
http = { version = "0.2.6" }
tokio = { version = "1.15.0", features = ["full"] }
tower = "0.4.11"
tower-http = { version = "0.2.1", features = ["request-id", "trace", "util"] }