[package]
name = "gargantua"
version = "0.1.0"
authors = ["Bryant Luk <bryant.luk@bryantluk.com>"]
edition = "2018"

[dependencies]
tide = "0.9"
async-std = { version = "1", features = ["attributes"]}
serde = "1"
serde_json = "1"
dotenv = "0.15"
log = "0.4"
env_logger = "0.4"
uuid = { version = "0.8", features = ["serde", "v4"] }
