[package]
name = "gargantua"
version = "0.1.1"
authors = ["Bryant Luk <bryant.luk@bryantluk.com>"]
edition = "2018"

[dependencies]
tide = "0.15"
http-types = "2"
async-std = { version = "1", features = ["attributes"]}
serde = "1"
serde_json = "1"
dotenv = "0.15"
log = "0.4"
env_logger = "0.4"
uuid = { version = "0.8", features = ["serde", "v4"] }
httpdate = "0.3.2"
async-trait = "0.1"
